### ISSUE TITLE
sendSticker :: Error

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#101]
I was found if sendSticker that we didnt purchase will result : 
`>>> h.sendSticker("13170847","7172","1","[null]")`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "C:\Python27\lib\site-packages\line\models.py", line 97, in sendSticker`
`    raise e`
`Exception: Error: You need to login first. There is no valid certificate`

Detailed sticker Info:
 - http://dl.stickershop.line.naver.jp/products/0/0/1/7172/android/stickers/13170847.png - sticker that i send
 - http://dl.stickershop.line.naver.jp/products/0/0/1/7172/android/productInfo.meta - list of sticker pakage image
 - http://dl.stickershop.line.naver.jp/products/0/0/1/7172/android/stickers.zip - download zip file

Name : 君の名は。
Ver : 1
PackageID : 7172

Is there someone can send sticker without purchase it first ?? :3
also on the JSON data of productInfo.meta the "price" data 0.00 it mean FREE. if isit why cant be used?

**Comment by max32002** [comment]
1) server side block the user send un-purchased sticker.
2) not all free sticker you can send it, you need get it before you can send. 
3) not all sticker info is included in the productinfo.meta file, ex: "Free available until day", "Sticker 
Country code", "Sticker description", "Is for Phone Operator limit".
for more free LINE Sticker info you can visit this facebook fan page: https://www.facebook.com/stickerline555/

**Comment by anysz** [comment]
ok got it
