### ISSUE TITLE
A Few Little thing :: Operation

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#102]
This Issue i made bcz i still confusing to Use this Lib.
First : 
 - To Login : client = LineClient("EMAIL", "PASSW")
 - To send message : client.getGroupByName("GROUP_NAME").sendMessage("MSG")
 - To update Token : client.updateAuthToken()
 - To print Token : client.authToken
 - To get Group Id : client.getGroupByName("GROUP_NAME").id
 - To send sticker : client.getGroupByName("GROUP_NAME").sendSticker("PIC_ID","PACK_ID","VER","[null]")
 - To Accept Group Invation : client.acceptGroupInvitation(client.getGroupById("GROUP_ID"))
 - To Leave Group : client.leaveGroup(client.getGroupById("GROUP_ID"))

Thats I know. i want to ask how to:
 - Get All member of group 
 - Get latest message 
 - sendImage
 - Invite Contact to join Group
 - Kick Contact from Group
 - Cancel specific Invitation on Group
 - Change display name 
 - Interval time to execute for not get deactivated

Someone i need your help to find out that function reply this or : 
Contact LINE -> http://line.me/ti/p/0mYD1NdaOr
Thanks

**Comment by theawangatang** [comment]
getting all group members. - check models.py Note: group members is list

getting latest message is not very necessary. to check for files create an if statement (if something in message.text)

sendImage - check models.py

invite contact to join group - check api.py its self._client.inviteIntoGroup(seq, id of group, target person)
- you need to derive missing info

kickout - see above but use kick in api.py

cancel works same way

change display name - reverse engineering curve python thrift files needed (very difficult)

use a loop or a ps1 in windows or crontab for unix based

**Comment by anysz** [comment]
i cant find any curve python thrift files. it should be located on
`File "build\bdist.win32\egg\curve\CurveThrift.py"`

i cant find CurveThrift.py file. is it packed on a file?

**Comment by theawangatang** [comment]
It's an import called Curve. It should be where all packages you pip install go. On Windows I found it in site-packages

**Comment by anysz** [comment]
its on .egg file but yeah zip and extract solve this problem

**Comment by anythingg** [comment]
I dont know what you mean by see above for kickout in the api.py. I found the line that says _kickout in the api.py but that does not tell me the command to use kickout. Can someone please tell me the command to use kickout? Sorry, I'm new to python.

**Comment by anysz** [comment]
client._kickoutFromGroup(group, [mid])

**Comment by ii64** [comment]
It was fun guys, Thanks. Issue fixed.
