### ISSUE TITLE
THRIFT ERROR :: CANCEL/KICK

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#103]
I was testing out and found some error

> <img src="https://puu.sh/v39b9/d165180b37.png"></img>

Does Thrift had bug eh?

**Comment by theawangatang** [comment]
make sure thrift == version 0.9.3

**Comment by anysz** [comment]
where `File "build\bdist.win32\egg\"` located ?

**Comment by mwahyu** [comment]
Help

**Comment by mwahyu** [comment]
#98

**Comment by anysz** [comment]
its not specific path to a file
`File "build\bdist.win32\egg\"`
