### ISSUE TITLE
SendChatChecked

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#106]
does Anyone know how to send it?
The lib can get but cant send.

**Comment by theawangatang** [comment]
What exactly is the function of this again. Sending a read receipt of some sort?

**Comment by anysz** [comment]
Yes. i was done found this

**Comment by R-N** [comment]
Were you able to make it work?

**Comment by anysz** [comment]
The answer is google :)

**Comment by ii64** [comment]
It was fun guys, Thanks. Issue fixed.
