### ISSUE TITLE
I can get my authToken in cmd but not when deployed to heroku. Any suggestions?

### ISSUE THREAD

**Issue by monhustla** [carpedm20/LINE#113]
I was able to log in via cmd just fine. When I deploy the repo to heroku, with changes to api.py, client.py, and gitignore I get the same "client is not defined" issue. Any suggestions?
<img width="691" alt="client is not defined" src="https://cloud.githubusercontent.com/assets/20822555/26665190/6c09a30a-465d-11e7-8eea-bd088d5bed06.PNG">

**Comment by monhustla** [comment]
I think it's because the version in the repo is 7.0, however the pip install is 8.2.
<img width="770" alt="version 7" src="https://cloud.githubusercontent.com/assets/20822555/26665302/432a17de-465e-11e7-8589-cebb6779a985.PNG">

**Comment by monhustla** [comment]
Where are y'all deploying this I guess is the question?

**Comment by R-N** [comment]
Heroku.

Remove the line package from requirements.txt
Copy the line folder, which has api.py etc inside, to your heroku app folder.

Add, stage, commit, push.

**Comment by R-N** [comment]
Of course, I meant the line folder which files you have modified.

**Comment by anysz** [comment]
i dont know if heroku support this,
