### ISSUE TITLE
Line@ protocol??

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#120]
So yea, I was discovered line@ and all I got is just "MessageAPI"
Which is hard for someone new. And I start sniffing line@ for its protocol 
The benefit is line@ account can get more than 50 and no need web for webhook which its need https web to work. Just wonder if its can work without MessageAPI :)

**Comment by dotcool** [comment]
hi...i wonder that this api can add friends or send spam messages

**Comment by anysz** [comment]
Yes its can add, and send message, just like LINE@ app on playstore,, but i dont see if its can join/kick on group

**Comment by dotcool** [comment]
hi, @anysz but how to add new friends . i success send message to my friends. but i want to add amount people with phone number .

**Comment by anysz** [comment]
Are you trying to add friend with carpedm20 lib or the line@?

If carpedm20 lib, just look function on api.py
Findandaddby....

**Comment by dotcool** [comment]
@anysz  i know it ,but the times limit. but mobile sync contact book don't limited .
So I want to implement sync mobile contacts . i find it's a tcp process not in thrift. do you know how to implement this function?

**Comment by anysz** [comment]
what function? not with thrift? 
can i know the tcp address path.
the one that sync Contact is getContacts([array of all friend mid])

**Comment by chobiz13** [comment]
@dotcool  @anysz 
for sync mobile contact there is possible way that you can do but as i know you have to do it manually. I also find the way to use CLI or any trick for this.

**Comment by anysz** [comment]
Thanks ;D

**Comment by ii64** [comment]
Thanks guys.
