### ISSUE TITLE
Can this be printed on echobot?→ "Enter pin code 7390 to your mobile phone

### ISSUE THREAD

**Issue by Mari2928** [carpedm20/LINE#121]
Is there anyone knows how to code to print the cmd line message on the web? I put the echobot on my web server and it's logging on with authtoken, but wondering if I can print the pin code on it.

**Comment by RichoDS** [comment]
please teach me how to install this

im newbie
someone please help me
(id LINE: cyber_sq)

**Comment by anysz** [comment]
Well you can use line lib for php so it much easier to get authtoken.
If its done, just load authtoken with python

**Comment by fadhiilrachman** [comment]
call php func exec('python login_line.py -s "email@dot.com" "passwd" ');
and you can extract all params from your python 'login_line.py'
then print the pin code from login_line.py
remake code in api.py at def login() and all are required into new self function and move to 'login_line.py'

that's all

**Comment by Nilpo** [comment]
Why not just log into your web server and tail the log file? That's where Python is writing the message anyway.

**Comment by Mari2928** [comment]
Thanks. I saved the pin code info into txt file on the server to view it online. However this api is no longer able to login and get authtoken.
