### ISSUE TITLE
Can't do updateAuthToken if I do it after 10 mins after getting a new authToken by logging in with email and password

### ISSUE THREAD

**Issue by R-N** [carpedm20/LINE#127]
I keep getting pinCode message (type 3) instead. Is it just me? Since I did mess with the API a lot. I've also tried my old backup which used to work just fine for more than a week without restarting, but it doesn't work anymore (Getting pinCode too).

It works if I logged in with email and password though. But if I restart it and log in with authToken which I just got by logging in with email, it also doesn't work. It's like the authToken only work with that one session.

I use Keep-Alive connection with THttpPersist I found here and don't close the connection manually, but it should've closed itself when the program exits, right?

Also, self.provider on client.py or api.py shouldn't have been set if I log in with authToken, right? But it's always used in loginWithIdentityCredentialForCertificate, which is in login() in LineAPI in api.py, which is called on updateAuthToken(). I tried to pass None for it but it raises Exception asking for provider. What could be in it? I used to set it with what it should've been if I log in with email, and it used to work.

**Comment by BloodySenpai** [comment]
Line updated something so most of us are having this issue

**Comment by R-N** [comment]
Ah, okay. I thought I broke the code somewhere haha. But this may mean I won't be getting the fix anytime soon lol.

Btw I tried the SSL Packet Sniffer for Android I found somewhere here to try to find a way to download image from messages.  Header X-LINE-ACCESS is supposed to be authToken or verifier right? With verifier being the short one. I don't know how it was before, but X-LINE-ACCESS keep changing in the packets I got (short one, long one, both), despite me never logging out, nor even closing the app. Maybe LINE now changes the authToken every so often.

**Comment by R-N** [comment]
I tried updating authToken more frequently, it didn't help.

I'll try not updating at all. Works fine so far even though I'm using the authToken which had failed to update (gave me pincode)

**Comment by R-N** [comment]
It lasted 3 hours. Guess I still need to update authToken afterall

**Comment by fadhiilrachman** [comment]
you just remake the old login function from line.thrift to the new login function in curve lib
and working again

**Comment by BloodySenpai** [comment]
Can you explain what you mean?

**Comment by BloodySenpai** [comment]
@fadhiilrachman Can you show an example of what you mean or any way to contact you?

**Comment by anysz** [comment]
thrift -gen py line.thrift

for the line.thrift you can download here

**Comment by anysz** [comment]
https://github.com/cslinmiso/LINE-instant-messenger-protocol/blob/master/line.thrift

if its done, just patch old curve with it like @fadhiilrachman said

**Comment by R-N** [comment]
I'm quite confused actually. So I should 'port' from the latest line.thrift to my curve lib? Or backporting from the latest curve lib to 0.9.3? And it's not the api.py?

The login function is the loginWithIdentityCredentialForCertificate right? Just to make sure since there are many login stuff on line.thrift but this one is the one used here in this lib.

Sorry, I'm not familiar with thrift. line.thrift only has what seems like structs to me. So I only need to change those 'structs' (args, result, write&read)? Or should I also copy the whole thing (send-recv functions from purple-line or somewhere (like I did with sendChatChecked)? Well I'll just try to copy all of them

Anyway, thanks for the lead. I'll try it tomorrow.

**Comment by R-N** [comment]
I just found out that the line.thrift can literally be used to generate a python code lol neat

**Comment by ii64** [comment]
I think this error is odd, you cant login with cert in curve, but you still can login with the gen one without need to reinput pin
「Removed SNS」

**Comment by max32002** [comment]
BOT work again by login by tokenLogin(). You have to modify def tokenLogin(self):  in api.py to assign self._headers again.

**Comment by R-N** [comment]
Wow you actually posted your lineId here. I was afraid of doing that, thinking LINE might found out and ban me lol. I've added you btw.

The issue persists. Are you having this issue too?

By the way the 'new' login function doesnt ask for keyname and crypto.

Also, what do you pass for identityProvider, id, and password if you login with authToken? Passing None or empty string for id and password gives me 'Account ID or Password is invalid' error (code 18). Passing 0 or 1 for provider didn't matter except when I actually pass my id and password.

If I log in with id and password, then I login with authtoken shortly after, it will succeed. I tried restarting my heroku 5 times just now, the fifth time didn't work. It was around 5-7 minutes in total. I'll try restarting after 10 minutes once just to see if the limit is tries or attempts.

Alright, one restart and it just doesn't work. I guess the limit is time. So I can't update authToken, huh

**Comment by R-N** [comment]
@max32002 the login() function always setCustomHeaders for _client before calling loginWithIdentityCredentialForCertificate. I don't set it from _client_out (S4) and _client_in (P4) but the login and updateAuthToken doesn't use _client_out at all.

**Comment by R-N** [comment]
Sorry I misunderstood.

Btw it's already resetting the headers for the _client. 

In my API I made it reset headers for all _clients though..

**Comment by R-N** [comment]
I messed up with ready(). I tried to print dir(self.transport) there without converting it to str first and it crashed.

I fixed it but still crashes saying LineAPI doesnt have _client, which shouldve been set in ready(). I ctrl+z ed all the way back but it still crashes. I tried printing some stuff there but they dont get printed. 

I thought my build doesnt get udpated, I tried to edit my main program to print some stuff and it worked. 

I don't know what's going on anymore lmao. Guess I'll just sleep.

**Comment by R-N** [comment]
_client error fixed, it was an error on my end, sorry.

I still can't update authtoken though, and the expiration time seem to shorten to 1 hour fml

**Comment by BloodySenpai** [comment]
@max32002 can you explain better ? I don't understand what you meant

**Comment by R-N** [comment]
I think I found a fix(?)

If you have authToken:
      if it's a get operation:
             use LINE_HTTP_IN_URL
      else:
             use LINE_HTTP_OUT_URL
else:
      use LINE_HTTP_URL to get authToken, then use LINE_HTTP_IN_URL

My bot has been up for 15 hours now, and it has never 'updated' authToken. I think it'll never expire on LINE_HTTP_IN_URL and LINE_HTTP_OUT_URL. By the way updateAuthToken works with LINE_HTTP_IN_URL, I didn't try with LINE_HTTP_OUT_URL though.

You can change those in api.py, when it defines self.transport

**Comment by max32002** [comment]
I write authToken to file after got it:
```
    def save_token_to_file(self):
        text_filename = "%s.token" % (self.id)
        text_file = open(text_filename, "w")
        text_file.write(self.authToken)
        text_file.close()

```

I read the autoToken from file, and if LINE response Error: 

> TalkException(parameterMap=None, reason='AUTHENTICATION_DIVESTED_BY_OTHER_DEVICE', code=8)
goto clean authToken, and login by id/password with pin code in device.

**Comment by R-N** [comment]
@max32002 Isnt that just what this lib has been doing all this time? Except it tries to 'updateAuthToken' first before logging in by id password and pincode.

**Comment by kasem123** [comment]
@R-N No, he means that you should ditch email/password login and use authToken instead
Basically, login with email/password, save authToken in a file (similar to the way .crt is saved) and use it later on when starting your bot
Downside is that authTokens aren't permanent and will require pincode later on (has been tested)
We've had different results from about 1 week to about 2 months on the same authToken

**Comment by R-N** [comment]
@kasem123 Oh right, it was only cert. Sorry. Well the email/password login was only to get authToken, as you said, since using email/password login would require pincode verification and it's a real hassle to do it everytime.

I guess days just isn't enough to say it won't expire huh, since it ranges up to 2 months. Have you been calling 'updateAuthToken' periodically or on error (on sendMessage) on those tests? Did those test LINE_HTTP_URL (v4/TalkService.do) or LINE_HTTP_IN_URL (P4) for its main client?

**Comment by kasem123** [comment]
@R-N Calling "updateAuthToken" requires you to have a valid crt, if you call that after your crt has been invalidated you'd get asked for pin. The bots were running tokenlogin(), fetchoperations and sendMessage() periodically. We basically had a few full functional bots when we did the tests

**Comment by anysz** [comment]
Guess who can login with cert again xD

**Comment by fadhiilrachman** [comment]
just making your bots slower that make you fell 'bypassing pin code issues'

**Comment by R-N** [comment]
While it does seem like it got slower, I actually couldn't do 'updateAuthToken' like I used to (which worked well for 2 months). When I said I had the issue it always gave me pincode message on every login() (loginWithIdentityCredentialForCertificate), and REVOKE error on any other get/fetch methods. Either the authToken or the certs got invalidated after 10 minutes on LINE_HTTP_URL (TalkService.do), at least in my case. 

tokenLogin() is basically just ready() chopped down. It's just 'reconnecting to server'. 

What updateAuthToken() does is calling login() (loginWithIdentityCredentialForCertificate) with cert and authToken, then recreating the connection.

TalkService.do was used for everything. 
S4 wasn't used, but actually sends notification, when TalkService.do doesn't. Hence LINE_HTTP_OUT_URL.
If S4 actually has its use, maybe P4 too?
It actually can be used for get/fetch methods, hence LINE_HTTP_IN_URL. But TalkService.do does what both IN and OUT do, why not just use that for everything?
X-LINE-ACCESS header is needed for S4 and P4, but not TalkService.do. 'updateAuthToken' does nothing on _client_out (S4), yet _client_out never throws authentication errors.
S4 and P4 doesn't need 'updateAuthToken', or it just has very long timeout. 
Tried to remove _client_in and make _client use LINE_HTTP_IN_URL (P4) instead. It worked. 'updateAuthToken' 'works' again, heck, I don't even need to do it periodically (which actually makes me wonder if 'updateAuthToken' really works, hence the quotation marks).
But then login() with email/password won't work, since P4 requires authToken. That's what TalkService.do seems to be for, to get authToken and cert, then proceed with S4 and P4. If you already have authToken and cert, no need for LINE_HTTP_URL (TalkService.do) at all (unless it has somehow expired).

I'm not actually using this library anymore, though. I now use one I generated myself with line.thrift you can find on Google. Though simply using that didn't fix my problem, it didn't help at all. Switching to HTTP_IN (P4) did. 

It worked for two days, until my heroku free dyno hours has ran out this afternoon lol. I think my authToken and cert will still be valid tomorrow. 

By the way, since I've solved my issue, I think I'll be closing this.

Reference : https://groups.google.com/forum/#!msg/line-python-developer/6T44blymCDg/zEwYxQv2AAAJ

**Comment by djruiayng** [comment]
Traceback (most recent call last):
  File "war.py", line 18, in <module>
    line = LINE("EJuYwmWfEUX3adxRvcP5.Z8DeyMFRPhJA0JZec/GGrq.0Z8+OghH33V1xR5vItyGQhuYqNIqmH5niyXaV9S0SPk=")
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/client.py", line 21, in __init__
    self.loginWithAuthToken(authToken=idOrAuthToken, appName=appName)
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/auth.py", line 193, in loginWithAuthToken
    self.__loadSession()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/linepy/auth.py", line 31, in __loadSession
    self.revision = self.poll.getLastOpRevision()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/akad/TalkService.py", line 4432, in getLastOpRevision
    return self.recv_getLastOpRevision()
  File "/data/data/com.termux/files/home/DHENZA/Dhenza7/akad/TalkService.py", line 4455, in recv_getLastOpRevision
    raise result.e
Dhenza7.akad.ttypes.TalkException: TalkException(code=8, reason='AUTHENTICATION_DIVESTED_BY_OTHER_DEVICE', parameterMap=None)
========================================================
Who can save me? I am stuck here.

**Comment by anysz** [comment]
I hate people do shit
