### ISSUE TITLE
Cant reply message when the sender is line user who has no User ID.

### ISSUE THREAD

**Issue by abcd476555** [carpedm20/LINE#19]
Here is my code for reply message with the sender's name.

	while True:
		op_list = []

		for op in client.longPoll():
			sender	= op[0]
			receiver = op[1]
			message  = op[2]

			print "sender = %s" % (sender)
			print "receiver = %s" % (receiver)
			print "message.text = %s" % (message.text)

			sender.sendMessage("[%s]: %s" % (sender.name, message.text))

		time.sleep(5);

I test to my spare line accounts. The one with Line User ID is work perfectly, but error with another one that has no Line User ID like this

	sender = None
	receiver = <LineContact blankblankblank>
	message.text = test
	Traceback (most recent call last):
		File "hello.py", line 32, in <module>
			sender.sendMessage("[%s]: %s" % (sender.name, message.text))
	AttributeError: 'NoneType' object has no attribute 'sendMessage'

**Comment by carpedm20** [comment]
Hmm.. I've never seen this error before but you can try

	while True:
		op_list = []

		for op in client.longPoll():
			sender	= op[0]
			receiver = op[1]
			message  = op[2]

			print "sender = %s" % (sender)
			print "receiver = %s" % (receiver)
			print "message.text = %s" % (message.text)

                        if sender:
				sender.sendMessage("[%s]: %s" % (sender.name, message.text))

		time.sleep(5);

If there are more issue for this, i'll change add error handler code for this.

**Comment by abcd476555** [comment]
The app not crash now.
But there is anyway to reply this kind of line user?

I try to manually add this guy(no line user id) as friend by mobile, and it's work!
After add him to friend manually, now my line-bot can reply the message as normal.

How to programmatically do that? because at the first time line-bot receieve the meaasge,
line-bot seen 'sender  = op[0]' as 'None'

**Comment by abcd476555** [comment]
Sorry Carpedm. It seems like I misunderstood the problem since the start. The problem is NOT when the user does not have Line User ID. 

The true problem is that the bot cannot reply messeges to users who have added friend with the bot but the bot has not added him back. When the bot receive these messeges, the bot perceive these users as non-object because the senders do not appear in client.contacts. On the other hand, there is no User ID when I call client.contacts. How to programmatically do that.

**Comment by carpedm20** [comment]
Add `findAndAddContactByUserid` method in 5fc6fd4f9b2f3ffcc618701fd660eb1f8c8c7da3

try

    client.findAndAddContactByUserid("USER_ID")

**Comment by cjltsod** [comment]
This happened when receive message from anonymous sender, who is not in client's contacts.

**Comment by carpedm20** [comment]
I see... Thanks for your work :smile:
