### ISSUE TITLE
Excuse me, I want use send image but I couldn't get it working.

### ISSUE THREAD

**Issue by squallcx** [carpedm20/LINE#21]
I try to use code:
client.contacts[0].sendImage(r'upload/images.jpg')

error:
  File "build\bdist.win32\egg\line\models.py", line 114, in sendImage
NameError: global name 'text' is not defined

Please tell me how to do, thank you very much

**Comment by carpedm20** [comment]
Error fixed 4cd5fe7240039e9896be8be33c3a6a604197c22c

try:

     pip install --upgrade django
