### ISSUE TITLE
Multiline messages

### ISSUE THREAD

**Issue by carpedm20** [carpedm20/LINE#24]
I've never think about this but someone need this..

**Comment by cjltsod** [comment]
@carpedm20 : What's this issue is? Sending message with multiple lines can simply use '\n' to achieve.
Anyone can't successfully send '\n' as a line break?

**Comment by carpedm20** [comment]
https://groups.google.com/forum/#!topic/line-python-developer/0v3AvtDN9ec

There was no further description about how he couldn't break the line..
If this is not a general issue, then I'd better close this one.

**Comment by suksit** [comment]
Without code sample I would guess he wrapped the text with single quotes instead of double quotes.

**Comment by akrus** [comment]
Code example is below:

```
try:
   client = LineClient("name", "password")
   group = client.getGroupByName("Group")
   message = "Text\nText"
   group.sendMessage(message)
except:
   print "Login Failed"
```

**Comment by carpedm20** [comment]
Good news :smile:

**Comment by pinfort** [comment]
if you try example
message = 'example\nsecond line'
don't work.

but,if you try example
message = "example\nsecond line"
it will work.
