### ISSUE TITLE
Exception - Bad protocol id in the message: 83

### ISSUE THREAD

**Issue by NitroXenon** [carpedm20/LINE#26]
I got a unknown Bad protocol id in the message: 83 exception.
This is my code :
https://github.com/NitroXenon/feed2line/blob/master/feed2line.py

If I call `sendToLine` separately to test, message will be sent to all of my contacts.
But if I call `sendToLine` in a loop, it throws a exception.
Any ide?

Exception log :
```
Traceback (most recent call last):
  File "feed2line.py", line 48, in <module>
    checkFeed();
  File "feed2line.py", line 42, in checkFeed
    sendToLine(newest,feed['entries'][0]['link'])
  File "feed2line.py", line 27, in sendToLine
    c.sendMessage("在小N的3C研究所發表的新文章 - " + title + " : " + link)
  File "/usr/local/lib/python2.7/dist-packages/line/client.py", line 80, in sendMessage
    raise e
thrift.protocol.TProtocol.TProtocolException: Bad protocol id in the message: 83
```

**Comment by cjltsod** [comment]
I think it's an unicode issue. 
Encode your message by str(unicode_message) MAY solve this problem, take a try.

**Comment by NitroXenon** [comment]
yes it works. thx a lot
