### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by webbhlin** [carpedm20/LINE#30]
Hi Sir, I installed apache thrift 0.9.2 and line package on my mac.  It looked like everything installed correctly, but I cannot make the simple login work.

>>> from line import LineClient
>>> c = LineClient("webbhlin@gmail.com", "xxxxxx")
Enter PinCode '8811' to your mobile phone in 2 minutes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/line/client.py", line 81, in __init__
    self.login()
  File "/Library/Python/2.7/site-packages/line/api.py", line 113, in login
    raise Exception("Code is removed because of the request of LINE corporation")
Exception: Code is removed because of the request of LINE corporation

**Comment by mefirst42** [comment]
look in the client.py at line 82 (or around that) and comment  self.ready() out

        if authToken:
            self.authToken = self._headers['X-Line-Access'] = authToken

            self.tokenLogin()
            #self.ready()
        else:
            if EMAIL_REGEX.match(id):
                self.provider = Provider.LINE # LINE
            else:
                self.provider = Provider.NAVER_KR # NAVER

            self.id = id
            self.password = password
            self.is_mac = is_mac

            self.login()
            #self.ready()   <<<<<<<<<<<<<<<<<<<<<<<<<<< comment this out

**Comment by cjltsod** [comment]
Please look into #11 
@mefirst42 , please remove your answer.

**Comment by mefirst42** [comment]
roger that

**Comment by webbhlin** [comment]
i think I know how to get authToken now.  thanks!
