### ISSUE TITLE
httplib.ReponseNotReady error from longPoll()

### ISSUE THREAD

**Issue by Otokiru** [carpedm20/LINE#34]
Hi all,
I got this ResponseNotReady error after i send message using:
client.getContactById(<some id>).sendMessage(<some msg>)

The other user manage to receive the msg, however i will get this error from client.longPoll()
![screen shot 2015-05-27 at 2 12 17 pm](https://cloud.githubusercontent.com/assets/2200634/7830021/c8aa7dc2-047a-11e5-99c5-9af403ede473.png)

I'm using the same set of codes from my other bot which is working fine and without any issues.
I'm not sure if the error occurs when 2 LINE account is logged in the same pc, but seperate terminal window...

**Comment by carpedm20** [comment]
Hmm.. can you show me the code that you used when this error happened?
Even though this is dirty, my temporal suggestion is make an try catch exception handler to bypass the response error.

    while True:
        try:
            for op in clinet.longPoll():
                pass # your code
        except:
            continue

**Comment by Otokiru** [comment]
It appears that my timer for other functions conflicts with longpoll, after removing the timer from my codes, its working fine. I have no choice but to seperate my other functions with timer on different scripts. I think you can close this. Thanks.

**Comment by carpedm20** [comment]
@Otokiru Good news :)
