### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by matthewfu** [carpedm20/LINE#37]
Hello there,

I just got my never account. And when I login with the code here I got 'Account ID or password is invalid' error, but I do see a record said "signed in" my sing-in log at NAVER dashbroad. Any idea?

**Comment by carpedm20** [comment]
Did you try with your_id@naver.com?

**Comment by matthewfu** [comment]
Yes I did.

I am wondering if I need to go through some extra verification or do some
setting on NAVER site.

Thanks for responding. ^^


On Wed, Jun 10, 2015 at 9:05 AM, Taehoon Kim <notifications@github.com>
wrote:

> Did you try with your_id@naver.com?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/carpedm20/LINE/issues/37#issuecomment-110549830>.
>



-- 


Matt

**Comment by matthewfu** [comment]
Here is my screenshot for your reference.

[image: Inline image 1][image: Inline image 2]

On Wed, Jun 10, 2015 at 11:03 AM, Matthew Fu <matthewfu.tw@gmail.com> wrote:

> Yes I did.
>
> I am wondering if I need to go through some extra verification or do some
> setting on NAVER site.
>
> Thanks for responding. ^^
>
>
> On Wed, Jun 10, 2015 at 9:05 AM, Taehoon Kim <notifications@github.com>
> wrote:
>
>> Did you try with your_id@naver.com?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/carpedm20/LINE/issues/37#issuecomment-110549830>.
>>
>
>
>
> --
>
>
> Matt
>



-- 


Matt

**Comment by carpedm20** [comment]
This is weird.. This is a new login error that I've never seen. How about test the code with another account?

**Comment by carpedm20** [comment]
Actually I am still possible to login with my_id@naver.com and my_password combination.

**Comment by matthewfu** [comment]
Hi, I am thinking if there's extra security for logging Line with Naver account.

Do I need to Link my Naver account to Line? I might miss something since I can not read Korean.

**Comment by anusoft** [comment]
I think your code is missing the Pin Verifiy part, but I cannot say more, good luck.

**Comment by carpedm20** [comment]
Anyway this is a login related issue where any problem can be occurred because of incomplete implementation of deleted code as @anusoft mentioned. So I will close this issue.
