### ISSUE TITLE
Get profile avatar

### ISSUE THREAD

**Issue by mapring0019** [carpedm20/LINE#39]
In object contact i saw some keys related with picture and had value such as: picturePath, pictureStatus. How can i get profile avatar? Could you give me some suggestion? :)

**Comment by carpedm20** [comment]
You can get the profile image link via:

    print client.contacts[0].profileImage

**Comment by mapring0019** [comment]
No it doesn't work!
`Traceback (most recent call last):
  File "lineTest.py", line 12, in <module>
    print client.contacts[0].profileImage
AttributeError: 'LineContact' object has no attribute 'profileImage'`

**Comment by carpedm20** [comment]
Did you update the library? You can update it via:

    $ pip install line --upgrade

**Comment by mapring0019** [comment]
Thanks! It works after i pull code :+1:
