### ISSUE TITLE
Push/Pull for _fetchOperations

### ISSUE THREAD

**Issue by anusoft** [carpedm20/LINE#40]
I've capture traffic and found that longPoll function use the _fetchOperations which is using _client:
```
api.py
self._client.fetchOperations(revision, count)
```
This _client is based on non-blocking pull endpoint which result in excessive uses of data
so I've changed to
```
api.py
return self._client_in.fetchOperations(revision, count)
```
which still receives event and not use too many calls and seem much faster, but this method is blocking.

I'm not sure if we should have two modes (blocking via _client_in and non-blocking via _client)  or not.

**Comment by BloodySenpai** [comment]
Does this make bot faster?

**Comment by anysz** [comment]
this work, i think the bot is still at the same speed. depend connection. 
if _client isnt respond it do nothing. the _client_in will make new call session automaticly. 

you can see message from line, if youre login you got a message that describe if you logged in on pc.
if you use _client_in you got twice
