### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by xOmNomNom** [carpedm20/LINE#50]
Encountered this problem while logging in. After I typed the username and password, it throws the error in the title.
![lineapidream](https://cloud.githubusercontent.com/assets/13808904/9288664/5d1fdcaa-437c-11e5-9cb2-c8b8cb2826ea.png)

**Comment by carpedm20** [comment]
Are you sure you implement the incomplete codes correctly? Login issue is highly related to the sensitive codes, I'll close this issue.
