### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by jackzett** [carpedm20/LINE#53]
Using the latest version of the API I get a list error, please take a look at it
---------------------------------------------------------------------------------------------------------------
Can't paste the code in here for some reason 
PASTEBIN link: http://pastebin.com/g4FzftK8
----------------------------------------------------------------------------------------------------------------
What am I doing wrong and how can I fix this? 
Please help me lol

**Comment by anusoft** [comment]
Change your password first.

**Comment by jackzett** [comment]
Its fine its just a test account

**Comment by DJ-666** [comment]
The # number is a member count not a group number.

**Comment by jackzett** [comment]
Oh well that explains a lot, but how do I get a group number instead of group count?
I haven't read the api through completely so when I have before I get an answer I will post the answer myself in here so others can learn from the mistake I made.

**Comment by whitesn** [comment]
Since you only have one group in your test account then it's client.groups[0]

or

client.getGroupByName( "GroupName" )

**Comment by carpedm20** [comment]
I think this issue is solved. If you need more question then comment here agian :smile:
