### ISSUE TITLE
Retrieving full size image from LineMessage?

### ISSUE THREAD

**Issue by whitesn** [carpedm20/LINE#54]
This is a copy from : https://groups.google.com/forum/#!topic/line-python-developer/6VyNAYu5ASI

Hi, I'm not really fond of python so I'm sorry if this question is quite dense.

So I tried retrieving the message, I got:
LineMessage (contentType=IMAGE, sender=<LineContact sender_name>, receiver=<LineGroup group_name #2>, msg="")

from models.py I found out the properties from LineMessage
        self._client
        self._message
        self.id 
        self.text
        self.hasContent
        self.contentType
        self.contentPreview
        self.contentMetadata
        self.sender
        self.receiver
        self.toType
        self.createdTime

message.text will return as "" (empty)
message.contentMetadata will return {'seq': '14'}, which I'm not sure as well what is this about
message.contentPreview will return the image preview.

I tried looking here then http://altrepo.eu/git/line-protocol/blob/master/line-protocol.md for the library used by Kim (the Author)

contentMetadata map with the following keys:
PREVIEW_URL = absolute URL for preview image
DOWNLOAD_URL = absolute URL for full-size image
PUBLIC = "TRUE" (haven't seen other values)
but from message.contentMetadata I can't find any of these (perhaps the protocol was altered?)

Any idea on how do I get the full size image from LineMessage?
Thanks a lot :)

**Comment by DJ-666** [comment]
Did you actually read the segment you quoted? Lol

It specifically says that the above contentMetadata map is for "Official Accounts" read below for the actual information you are looking for.


"For normal image messages, a preview image is included as a plain JPEG in the contentPreview field. However, for some reason the official desktop client seems to ignore it and rather downloads everything from the object storage server.

The preview image URLs are http://os.line.naver.jp/os/m/MSGID/preview and the full-size image URL are http://os.line.naver.jp/os/m/MSGID where MSGID is the message's id field."

**Comment by whitesn** [comment]
Oh yeah my bad... but the URL doesn't seem to work as well for message images

**Comment by anusoft** [comment]
Some of them may store in difference datacenter for example: obs.line-apps.com or obs-sg or obs-th

**Comment by carpedm20** [comment]
Hmm this is possible. If we have a concrete or possible list of server for
image, we can update codes to try different servers.

**Comment by anusoft** [comment]
obs.line-apps.com
obs-beta.line-apps.com
obs-beta1.line-apps.com
obs-beta2.line-apps.com
obs-beta3.line-apps.com
obs-beta4.line-apps.com
obs-rc.line-apps.com
obs-rc1.line-apps.com
obs-rc2.line-apps.com
obs-kr.line-apps.com
obs-jp.line-apps.com
obs-tw.line-apps.com
obs-th.line-apps.com
obs-cn.line-apps.com
obs-us.line-apps.com
obs-sg.line-apps.com
obs-de.line-apps.com
obs-vn.line-apps.com
pd.rts.line.naver.jp

**Comment by carpedm20** [comment]
Quite a big list, should check them in multiple threads.

**Comment by whitesn** [comment]
Does the official line app also does it with bruteforce from the list?

**Comment by anusoft** [comment]
https://obs.line-apps.com/talk/m/download.nhn?oid=XXX

Try this URL (You'll need x-line-access: Header) :)

**Comment by whitesn** [comment]
@anusoft oid is the message.id, I still get 403

```HTTP
GET /talk/m/download.nhn?oid=<message_id> HTTP/1.1
Host: obs.line-apps.com
User-Agent: DESKTOP:WIN:5.1.2600-XP-x64(4.1.3.586)
X-Line-Access: <token>
X-Line-Application: DESKTOPWIN\t4.1.3.586\tWINDOWS\t5.1.2600-XP-x64
Cache-Control: no-cache
```

**Comment by anusoft** [comment]
These two links work for me:

```
curl -v 'https://obs.line-apps.com/os/m/XXX' \
-H $'X-Line-Application: DESKTOPMAC\t4.1.0\tMAC\t10.10.5-LEOPARD' \
-H 'X-Line-Access: XXX' \
-H 'User-Agent: DESKTOP:DESKTOP:MAC:10.10.5(4.1.0)' \
--compressed >a.png


curl -v 'https://obs.line-apps.com/talk/m/download.nhn?oid=XXX' \
-H $'X-Line-Application: DESKTOPMAC\t4.1.0\tMAC\t10.10.5-LEOPARD' \
-H 'X-Line-Access: XXX' \
-H 'User-Agent: DESKTOP:DESKTOP:MAC:10.10.5(4.1.0)' \
--compressed >a.png
```

**Comment by whitesn** [comment]
Oh it worked out with curl, I tried out it with [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en) and I'm not sure what is the dollar sign after -H means, but it seems to be the cause.. Thanks for the help, I'll try to figure this out :)

**Comment by anusoft** [comment]
@whitesn $ in bash shell means send \t as Tab.

**Comment by whitesn** [comment]
Alright, it works with python requests after I tried, I guess it was probably because postman was sending extra headers. Thanks a bunch @anusoft

**Comment by pinfort** [comment]
I think messageid is not objetid.

**Comment by pinfort** [comment]
message.id is numeric.
but,we need object id.
not message id.
object id start with 0m.
example LineAPI()._getGroups(groupids)[0].pictureStatus

**Comment by aimods** [comment]
I'm not sure but this what's I found on my mobile
![screenshot_2016-05-16-21-48-51](https://cloud.githubusercontent.com/assets/1587297/15293479/565627ee-1bb2-11e6-94f3-a0572d2df19e.jpg)

**Comment by pinfort** [comment]
![2016-05-17-00-10-26](https://cloud.githubusercontent.com/assets/19170349/15293740/636bdf02-1bc4-11e6-99b2-37c5b8ea5c1e.jpg)
oh, I see this picture in my phone, so I think we can't use messageid to get picture.

**Comment by FrozenFighter** [comment]
@aimods @pinfort Could you tell me what program did you use for capture line packet.

**Comment by pinfort** [comment]
@FrozenFighter 
this.
https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture

**Comment by MrSwiss** [comment]
@pinfort Thank you very much.

**Comment by pinfort** [comment]
@MrSwiss
Not at all.

**Comment by fpitlok** [comment]
Thanks ^_^
