### ISSUE TITLE
line login erorr

### ISSUE THREAD

**Issue by g00dStar** [carpedm20/LINE#55]
As for the version of LINE for Mac which is going to log in, support is finished now.
Please update LINE in the most recent version.

You input to the address bar of the update method browser of LINE for Mac with "http ://m e2.do/5uXxVIxR" or search LINE by iTunes, and please download the most recent version.

After having updated it in the most recent version, please try LIN E for Chrome when you cannot start LINE.
http://me2.do/5Qq0ZU3g
-------------------------------

**Comment by whitesn** [comment]
I think you are in the wrong section buddy, this is not official LINE app forum / helpdesk

**Comment by carpedm20** [comment]
@whitesn Thanks for your clear answer.
