### ISSUE TITLE
who use??

### ISSUE THREAD

**Issue by g00dStar** [carpedm20/LINE#56]
for op in client.longPoll():

It anything other than the use ?

**Comment by whitesn** [comment]
longPoll() is basically the same verbose, to fetch all the operations happening in the background (received chat, read notification, etc.).

**Comment by whitesn** [comment]
longPoll() is basically the same verbose, to fetch all the operations happening in the background (received chat, read notification, etc.).

**Comment by g00dStar** [comment]
ok !
you have a line bot??

**Comment by whitesn** [comment]
I made a little BOT for mirroring image, please close the issue if you are done with it. If you want to have further discussion, we can have a chat on gitter or via PMs :)

**Comment by g00dStar** [comment]
ok thank's

what name gitter on suggested room??

**Comment by whitesn** [comment]
[#carpedm20/LINE](https://gitter.im/carpedm20/LINE?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by carpedm20** [comment]
The question is too general and no details. Please write a detailed question and reopen this issue again :smile:
