### ISSUE TITLE
re-type pin code with certificate

### ISSUE THREAD

**Issue by sschang123** [carpedm20/LINE#59]
While I login on some device first time success, I can get a certificate.
After this, I can use certificate to login without type pin code again.
But I got a strange scenario. Sometimes I need to type pin code again even I have certificate.
Does anyone have such situation? Is there any solution for this?
Thank you.

**Comment by carpedm20** [comment]
Its because the session is expired.. You need to call `updateAuthToken ` sometimes before the session is expired.
