### ISSUE TITLE
loginWithVerifierForCertificate failed [Login]

### ISSUE THREAD

**Issue by gokusenz** [carpedm20/LINE#60]
Today Line change somethings about certificate.

File "line/client.py", line 88, in **init**
    self.login()
File "line/api.py", line 147, in login
    msg = self._client.loginWithVerifierForCertificate(self.verifier)

thrift.Thrift.TApplicationException: loginWithVerifierForCertificate failed: unknown result

How can i fix it?

Thank you

**Comment by noflame** [comment]
The same thing happen to my bot. Can't get authtoken anymore...

**Comment by noflame** [comment]
It is fine after update line module.
pip install -U line

**Comment by liviuchircu** [comment]
I'm getting the same thing, after I managed to get the token and used it a couple of times. Hope it's just  temporary, so I can keep working on the bot...
