### ISSUE TITLE
LINE Messages Delayed

### ISSUE THREAD

**Issue by AndyAng1991** [carpedm20/LINE#65]
Hello, I want to ask why my messages when sending using the code delayed?And sometimes when I`m opening the chat from my tablet the messages instantly sent. :O

I'm using `client.contacts[53].sendMessage("ABCD ZYX 5")` to sent the messages

For info, the messages timestamp when received is the time when I'm sending the messages but the actual time needed to received the messages was longer than that.. about 7 minutes in my second experiment

**Comment by kslweb** [comment]
hi, by the way did you have any issues with blocking ?

**Comment by AndyAng1991** [comment]
@kslweb I'm sorry, but what blocking?do you mean blocking in LINE?

**Comment by kslweb** [comment]
yes your ip got blocked when you are trying to login in line python.

**Comment by AndyAng1991** [comment]
@kslweb No, the messages is being sent properly, just it was delayed to some extend. Like when I'm sent it from python at 16:50, but the messages was received at 16:57. The weird thing is the time stamp show time 16:50 correctly. 

Note : the messages was sent to a LINE Client in android

**Comment by kslweb** [comment]
wow how could you login LINE without got an ip blocked ? did you use a VPN?

**Comment by AndyAng1991** [comment]
@kslweb I'm using authtoken. Is that whats usually happen when tryng to login into LINE (ip blocked thing) ? That's not happen in my case though..

**Comment by kslweb** [comment]
i've an issue like this.
https://github.com/carpedm20/LINE/issues/66
did you know how to handle it?

**Comment by kslweb** [comment]
@AndyAng1991

**Comment by tanaboon** [comment]
@AndyAng1991 
I have same issue in the topic
It delayed and cannot receive sound alert on mobile.

**Comment by ids93216** [comment]
I have this problem too
The solution is POST data to /S4 path

And the way to fix it, you should edit code in api.py

You should add a line in about line 39 in api.py
`LINE_HTTP_OUT_URL       = LINE_DOMAIN + "/S4"`

And in "self.transport" and "self._client", copy a line and add "_out"
like "self.transport_out" and "self._client_out"

Then find "def _sendMessage"
And change "return self._client" to "return self._client_out"

That will be works fine

Sorry for my poor English

**Comment by ids93216** [comment]
![image](https://cloud.githubusercontent.com/assets/4828920/14452526/cec259ac-00c1-11e6-9652-287e0e4b647c.png)
![image](https://cloud.githubusercontent.com/assets/4828920/14452547/f5f9ca1e-00c1-11e6-93d9-6260dea410e6.png)
![image](https://cloud.githubusercontent.com/assets/4828920/14452558/03068c6a-00c2-11e6-988f-787122254c5c.png)

Like this.

**Comment by AndyAng1991** [comment]
it works like a charm!! 
thanks @ids93216

**Comment by tanaboon** [comment]
![image](https://cloud.githubusercontent.com/assets/16379670/14554962/1dd729dc-031a-11e6-8d50-5e6ca5fb37a5.png)

I change "return self._client" to "return self._client_out"

**Comment by AndyAng1991** [comment]
@tanaboon 
you need to do like @ids93216  shows. The attribute need to be added in the login function and tokenlogin function if you login using token.

**Comment by tanaboon** [comment]
![image](https://cloud.githubusercontent.com/assets/16379670/14557632/6e2c2d7a-0328-11e6-8cdc-bb8049732966.png)
![image](https://cloud.githubusercontent.com/assets/16379670/14557663/97116ee4-0328-11e6-9799-383d945b2c25.png)
![image](https://cloud.githubusercontent.com/assets/16379670/14557707/bbc610a0-0328-11e6-94c5-8fbad065fd05.png)

**Comment by ids93216** [comment]
@tanaboon Don't touch models.py, just edit api.py

**Comment by tanaboon** [comment]
@ids93216
I dont' touch models.py and i try to copy and replace  new models.py
and still error same this post

Thanks @ids93216 , AndyAng1991

**Comment by R-N** [comment]
I tried this but now I can't even send messages. So I reverted back. Is there any way to somehow make this work again, or am I doing something wrong? I did as shown in the picture.

**Comment by anysz** [comment]
its should work then @R-N

**Comment by R-N** [comment]
My bad. I changed every _client to _client_out. I shouldnt have done that in models.py. the _client in LineBase actually refer to a LineClient, not a CurveThrift.Client
