### ISSUE TITLE
Line Group URL

### ISSUE THREAD

**Issue by pinfort** [carpedm20/LINE#73]
Can I get Group URL by this api ?
example
http://line.me/ti/g/xxxxxxxxxx

**Comment by pinfort** [comment]
I resolved this issue.

**Comment by tmjvonboss** [comment]
How did you resolve this issue?

**Comment by anysz** [comment]
wtf how dude

**Comment by infinitylabs** [comment]
Anyway you can share how you got this fixed? Been struggling for a few days on this.

**Comment by tmjvonboss** [comment]
You just call a thrift method for it, its not an attribute of the group object
