### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by theawangatang** [carpedm20/LINE#90]
After making a bot that was functional for a long duration of time, for some reason when attempting to login, I receive an error which states that no JSON object can be read. It began after LINE supposedly began maintenance on their servers.

The error:

  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by theawangatang** [comment]
Also, the missing code I filled in has worked fine for weeks. This issue started yesterday and affected 3 other people I know who make Python bots for LINE.

**Comment by theawangatang** [comment]
I took care of it.

**Comment by chungsir** [comment]
how to slove it hlep me

**Comment by BloodySenpai** [comment]
Is this a way you can tell us how to fix it?
