### ISSUE TITLE
Same issue with json having trouble to decode

### ISSUE THREAD

**Issue by BloodySenpai** [carpedm20/LINE#93]
File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Anyone way I can fix this error?

**Comment by max32002** [comment]
because of no json was response from line server: http://gd2.line.naver.jp/authct/v1/keys/line

**Comment by BloodySenpai** [comment]
Do you know a way I can fix this?

**Comment by BloodySenpai** [comment]
Please

**Comment by shinomura** [comment]
because of 'X-Line-Application' is set in client.py 
i found that if this header set the server won't return json, so just disable it
#self._headers['X-Line-Application'] = app

but i still got error in getLastOpRevision()

**Comment by BloodySenpai** [comment]
You will still get a buffer error

**Comment by shinomura** [comment]
I'm very newbie for python but after found this and tried for 3 days, now I'm stucking on this error. both with id and pass and authtoken login

Login Failed
Traceback (most recent call last):
  File "D:\WinPython-32bit-2.7.x\LINE\build\bdist.win32\echobot.py", line 6, in
<module>
        client = LineClient("xxx", "xxx")
  File "D:\WinPython-32bit-2.7.x\LINE\build\bdist.win32\line\client.py", line 89
, in __init__
    self.login()
  File "D:\WinPython-32bit-2.7.x\LINE\build\bdist.win32\line\api.py", line 132,
in login
    self.com_name, self.provider, self.certificate)
  File "build\bdist.win32\egg\curve\CurveThrift.py", line 344, in loginWithIdent
ityCredentialForCertificate
    return self.recv_loginWithIdentityCredentialForCertificate()
  File "build\bdist.win32\egg\curve\CurveThrift.py", line 363, in recv_loginWith
IdentityCredentialForCertificate
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "D:\WinPython-32bit-2.7.x\python-2.7.10\lib\site-packages\thrift\protocol
\TCompactProtocol.py", line 310, in readMessageBegin
    proto_id = self.__readUByte()
  File "D:\WinPython-32bit-2.7.x\python-2.7.10\lib\site-packages\thrift\protocol
\TCompactProtocol.py", line 289, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "D:\WinPython-32bit-2.7.x\python-2.7.10\lib\site-packages\thrift\transpor
t\TTransport.py", line 63, in readAll
    raise EOFError()
EOFError

**Comment by BloodySenpai** [comment]
You need an api url that's because you disabled the header

**Comment by shinomura** [comment]
I only disable it before getson I added it back after that. but it still show above error

TTransport.py", line 63, in readAll
raise EOFError()
EOFError

if login with id and pass it error in def login at
msg = self._client.loginWithIdentityCredentialForCertificate(
                self.id, self.password, keyname, crypto, True, self.ip,
                self.com_name, self.provider, self.certificate)

if login with authtoken it error in client.py at
self.revision = self._getLastOpRevision()

**Comment by shinomura** [comment]
ok, now I can login and get authtoken

as I said before, for who can't login just disable header "X-Line-Application" before get json and add it back after that and change LINE_DOMAIN from http to https

don't forget to replace code in api.py at def ready if you want to login with id and pass

**Comment by BloodySenpai** [comment]
Do you have line? Where I can contact you because I don't understand what you mean

**Comment by BloodySenpai** [comment]
Nvm thank you

**Comment by crazy-ace003** [comment]
I tired what you said to do, but im getting a client is not defined. I have the right version, anyone getting or got the issue

**Comment by max32002** [comment]
I tired what you said to do, amazing! It's work again!

in the def login(self): in api.py
        self._headers['X-Line-Application']=app
        self.transport.setCustomHeaders(self._headers)

shinomura: now I can login and get authtoken
> 1.disable header "X-Line-Application" before get json
> 2.add it back after that then change LINE_DOMAIN from http to https

**Comment by crazy-ace003** [comment]
So I disable header  "x -Line-Application" but what do you mean by add it later.., Like after u get auth_token?

**Comment by chungsir** [comment]
in client.py disable self._headers['X-Line-Application']=app
then in api.py
in def login(self):


j = self.get_json(self.LINE_CERTIFICATE_URL)

add:
self._headers['X-Line-Application']=app
self.transport.setCustomHeaders(self._headers)
can work 


thanks everybody
