### ISSUE TITLE
Does line let you send images still.

### ISSUE THREAD

**Issue by BloodySenpai** [carpedm20/LINE#94]
Bot pauses after trying to send image

**Comment by FrozenFighter** [comment]
@BloodySenpai  Can you make pull request to update this git with your working files.
Thanks

**Comment by BloodySenpai** [comment]
Fix is simple like the guy before stated.
go to api.py
line 36 : change the http to https
That's it

**Comment by FrozenFighter** [comment]
Thanks, I have try to send Image its working fine. I think you may have some kind of ip ban. Please try to change your ip.

**Comment by BloodySenpai** [comment]
it's not ip ban or it wouldn't respond to messages. do you have line?

**Comment by FrozenFighter** [comment]
I have but I don't want to post it public Line maybe ban me.
I didn't do anything special just change to use SSL.

**Comment by BloodySenpai** [comment]
explain what you mean?

**Comment by FrozenFighter** [comment]
I use notepad++ "Replace in Files" function[Ctr+F]
To replace every http:// with https:// in LINE folder[folder that has __init__.py, api.py, client.py, models.py]
and do "python setup.py install"

Sorry, for my bad English

**Comment by BloodySenpai** [comment]
thank you it's cool

**Comment by BloodySenpai** [comment]
anything where I can contact you?

**Comment by FrozenFighter** [comment]
Does it not fix your issue?

**Comment by BloodySenpai** [comment]
No

**Comment by shinomura** [comment]
in models.py at
r = self._client.post_content('https://os.line.naver.jp/talk/m/upload.nhn', data=data, files=files)

change os.line.naver.jp to obs.line-apps.com

**Comment by Saixiii** [comment]
otherwiase change https://os.line.naver.jp/talk/m/upload.nhn to
**http://os.line.naver.jp/talk/m/upload.nhn**  ( http://)

**Comment by BloodySenpai** [comment]
I tried https://obs.line-apps.com/talk/m/upload.nhn before but it wasn't working until I tried again thanks
