### ISSUE TITLE
Cant Login 

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#96]
i had code like :
`from line import LineClient, LineGroup, LineContact`
`global sender`
`global reciver`
`global` `message`

`try:`
    `client` `=` `LineClient("nxxx@anysz.esy.es",` `"nxxxxx")`
    `#client` `=` `LineClient(authToken="AUTHTOKEN")`
`except:`
    `print` `"Login` `Failed"`

i execute that code on cmd
 `D:\Server>echobot.py`
they return
> 
Login Failed
> 

Is there anything wrong with the class or something else?

**Comment by max32002** [comment]
I try to execute that code on command, they return:
Enter PinCode '9603' to your mobile phone in 2 minutes

Your answer at here:
https://github.com/carpedm20/LINE/issues/93

**Comment by anysz** [comment]
I think its not about the json code. because 
`D:\LINE\I\examples>echobot.py`
`Login Failed`
`Traceback (most recent call last):`
`  File "D:\LINE\I\examples\echobot.py", line 12, in <module>`
`    for op in client.longPoll():`
`NameError: name 'client' is not defined`

op not defined because it dont get any data.  im newbie at python.

does Message protocol can be run at php?
thats it

**Comment by anysz** [comment]
I`ve Edit some code and its be like
`from api import LineAPI`
`from client import LineClient`
`from models import LineMessage, LineBase, LineGroup, LineRoom, LineContact`

`try:`
    `client = LineClient()`
    `client = LineClient("MY_LINE_ID", "THE_PASS")`
    `#client = LineClient(authToken="AUTHTOKEN")`
	
`except:`
    `print "Login Failed"`

its return False and show 
`D:\LINE\I\examples>echobot.py`
`Login Failed`

Is there something that i need to change?

**Comment by BloodySenpai** [comment]
Thrift wasn't installed correctly lmao

**Comment by anysz** [comment]
BloodySenpai: I was install it correctly now.
but i got another error
`>>> from line import LineClient, LineGroup, LineContact`
`>>> client = LineClient("nxxxx@anysz.esy.es", "xxxxxx")`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
 ` File "C:\Python27\lib\line\client.py", line 88, in __init__`
`    self.login()`
`  File "C:\Python27\lib\line\api.py", line 88, in login`
`    j = self._get_json(self.LINE_SESSION_LINE_URL)`
`  File "C:\Python27\lib\line\api.py", line 335, in _get_json`
`    return json.loads(self._session.get(url, headers=self._headers).text)`
`  File "C:\Python27\lib\json\__init__.py", line 339, in loads`
`    return _default_decoder.decode(s)`
`  File "C:\Python27\lib\json\decoder.py", line 364, in decode`
`   obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode`
`    raise ValueError("No JSON object could be decoded")`
`ValueError: No JSON object could be decoded`
`>>>`

Anyone help pls

**Comment by nightwing25** [comment]
sammeeee

Login Failed
Traceback (most recent call last):
  File "echobot.py", line 12, in <module>
    for op in client.longPoll():
NameError: name 'client' is not defined

**Comment by anythingg** [comment]
does anyone know where i can find the login bypass script?

**Comment by ii64** [comment]
It was fun guys, Thanks. Issue fixed.
