### ISSUE TITLE
Unicode buffer

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#98]
It works propertly until api.py want to connect to the server

> <img src="https://puu.sh/uUaaH/9c22915c43.png"></img>

Anyone had solution?

**Comment by max32002** [comment]
https://github.com/carpedm20/LINE/issues/88

**Comment by anysz** [comment]
So I need downgrade my Apache thrift from 10.0 to 9.x ?

**Comment by theawangatang** [comment]
pip uninstall thrift
pip install thrift==0.9.3

**Comment by anysz** [comment]
downgrade thrift from 10 to 9.3 Thanks

**Comment by brendhadhea** [comment]
how to install thrift 0.9.3 in raspberry pi??

**Comment by anysz** [comment]
I just copying all lib on python that already had thrift.

**Comment by Nilpo** [comment]
Downgrading from Thrift 10.0 to 9.3 does not resolve this issue for me.

**Comment by Nilpo** [comment]
@brendhadhea You can use `wget http://archive.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz` to download the archived version and then follow the general instructions found [here](https://thrift.apache.org/docs/install/debian) and [here](https://thrift.apache.org/docs/BuildingFromSource). I have used this installation method in Raspbian Jessie.

**Comment by Nilpo** [comment]
I got it sorted. Pip was installing Thrift 0.10.0 behind the scenes!

```
# following the normal install procedure...
python setup.py install
pip uninstall thrift      # version 0.10.0 will have been forcefully installed by the last command and will be the default
pip install thrift==0.9.3
```

Alternatively, you can use `easy_install` instead of `pip`.

**Comment by anythingg** [comment]
i did  "pip uninstall thrift"   but while uninstalling i got stuck in the console
so i closed mingw32 and opened it then did "pip install thrift==0.9.3" that installed it 
but now I get this error

user4@WIN-RA9GLN48TOF ~
$ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    client = LineClient("id", "password")
  File "C:\MinGW\msys\1.0\home\user4\line\client.py", line 88, in __init__
    self.login()
  File "C:\MinGW\msys\1.0\home\user4\line\api.py", line 130, in login
    self.com_name, self.provider, self.certificate)
  File "c:\Python27\lib\site-packages\curve\CurveThrift.py", line 344, in loginWithIdentityCredentialForCertificate
    return self.recv_loginWithIdentityCredentialForCertificate()
  File "c:\Python27\lib\site-packages\curve\CurveThrift.py", line 375, in recv_loginWithIdentityCredentialForCertificate
    raise result.e
curve.ttypes.TalkException: TalkException(parameterMap=None, reason='Account ID and password does not match', code=18)

i think thrift didnt unistall and I did put the correct password. can someone help me?

**Comment by Nilpo** [comment]
You should try running this in Vagrant or another virtual machine so you can install the dependencies on a clean system and bit have to worry about conflicts with anything on your system.

**Comment by anythingg** [comment]
I set up a new clean vm like you said but now I get this error when I run "python setup.py install"

user4@WIN-RA9GLN48TOF ~
$ python config.py

user4@WIN-RA9GLN48TOF ~
$ python setup.py install
running install
running bdist_egg
running egg_info
creating line.egg-info
writing requirements to line.egg-info\requires.txt
writing line.egg-info\PKG-INFO
writing top-level names to line.egg-info\top_level.txt
writing dependency_links to line.egg-info\dependency_links.txt
writing manifest file 'line.egg-info\SOURCES.txt'
reading manifest file 'line.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'line.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\line
copying line\api.py -> build\lib\line
copying line\client.py -> build\lib\line
copying line\models.py -> build\lib\line
copying line\__init__.py -> build\lib\line
creating build\bdist.win32
creating build\bdist.win32\egg
creating build\bdist.win32\egg\line
copying build\lib\line\api.py -> build\bdist.win32\egg\line
copying build\lib\line\client.py -> build\bdist.win32\egg\line
copying build\lib\line\models.py -> build\bdist.win32\egg\line
copying build\lib\line\__init__.py -> build\bdist.win32\egg\line
byte-compiling build\bdist.win32\egg\line\api.py to api.pyc
byte-compiling build\bdist.win32\egg\line\client.py to client.pyc
byte-compiling build\bdist.win32\egg\line\models.py to models.pyc
byte-compiling build\bdist.win32\egg\line\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
copying line.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying line.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying line.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying line.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying line.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\line-0.8.2-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing line-0.8.2-py2.7.egg
Removing c:\python27\lib\site-packages\line-0.8.2-py2.7.egg
Copying line-0.8.2-py2.7.egg to c:\python27\lib\site-packages
line 0.8.2 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\line-0.8.2-py2.7.egg
Processing dependencies for line==0.8.2
Searching for rsa
Reading https://pypi.python.org/simple/rsa/
Download error on https://pypi.python.org/simple/rsa/: [SSL: CERTIFICATE_VERIFY_FAILED] certifi                                                                                                           cate verify failed (_ssl.c:661) -- Some packages may not be found!
Couldn't find index page for 'rsa' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate                                                                                                            verify failed (_ssl.c:661) -- Some packages may not be found!
No local packages or working download links found for rsa
error: Could not find suitable distribution for Requirement.parse('rsa')

**Comment by anythingg** [comment]
when i do "pip uninstall thrift" it hangs at the end and i am stuck in python interpreter so i type exit() but it doesnt work, im still stuck in python interpreter.  so i close mingw32 and open it then run "pip uninstall thrift" only to find out that thrift 0.10.0 is still installed and still never finishes uninstalling and i get stuck in python interpreter again, no matter how many times i try.  how can i uninstall thrift 0.10.0 if this keeps happening?


user4@WIN-RA9GLN48TOF ~
$ pip uninstall thrift
Uninstalling thrift-0.10.0:
  c:\python27\lib\site-packages\thrift-0.10.0-py2.7.egg-info
  c:\python27\lib\site-packages\thrift\__init__.py
  c:\python27\lib\site-packages\thrift\__init__.pyc
  c:\python27\lib\site-packages\thrift\__init__.pyo
  c:\python27\lib\site-packages\thrift\compat.py
  c:\python27\lib\site-packages\thrift\compat.pyc
  c:\python27\lib\site-packages\thrift\compat.pyo
  c:\python27\lib\site-packages\thrift\protocol\__init__.py
  c:\python27\lib\site-packages\thrift\protocol\__init__.pyc
  c:\python27\lib\site-packages\thrift\protocol\__init__.pyo
  c:\python27\lib\site-packages\thrift\protocol\tbase.py
  c:\python27\lib\site-packages\thrift\protocol\tbase.pyc
  c:\python27\lib\site-packages\thrift\protocol\tbase.pyo
  c:\python27\lib\site-packages\thrift\protocol\tbinaryprotocol.py
  c:\python27\lib\site-packages\thrift\protocol\tbinaryprotocol.pyc
  c:\python27\lib\site-packages\thrift\protocol\tbinaryprotocol.pyo
  c:\python27\lib\site-packages\thrift\protocol\tcompactprotocol.py
  c:\python27\lib\site-packages\thrift\protocol\tcompactprotocol.pyc
  c:\python27\lib\site-packages\thrift\protocol\tcompactprotocol.pyo
  c:\python27\lib\site-packages\thrift\protocol\tjsonprotocol.py
  c:\python27\lib\site-packages\thrift\protocol\tjsonprotocol.pyc
  c:\python27\lib\site-packages\thrift\protocol\tjsonprotocol.pyo
  c:\python27\lib\site-packages\thrift\protocol\tmultiplexedprotocol.py
  c:\python27\lib\site-packages\thrift\protocol\tmultiplexedprotocol.pyc
  c:\python27\lib\site-packages\thrift\protocol\tmultiplexedprotocol.pyo
  c:\python27\lib\site-packages\thrift\protocol\tprotocol.py
  c:\python27\lib\site-packages\thrift\protocol\tprotocol.pyc
  c:\python27\lib\site-packages\thrift\protocol\tprotocol.pyo
  c:\python27\lib\site-packages\thrift\protocol\tprotocoldecorator.py
  c:\python27\lib\site-packages\thrift\protocol\tprotocoldecorator.pyc
  c:\python27\lib\site-packages\thrift\protocol\tprotocoldecorator.pyo
  c:\python27\lib\site-packages\thrift\server\__init__.py
  c:\python27\lib\site-packages\thrift\server\__init__.pyc
  c:\python27\lib\site-packages\thrift\server\__init__.pyo
  c:\python27\lib\site-packages\thrift\server\thttpserver.py
  c:\python27\lib\site-packages\thrift\server\thttpserver.pyc
  c:\python27\lib\site-packages\thrift\server\thttpserver.pyo
  c:\python27\lib\site-packages\thrift\server\tnonblockingserver.py
  c:\python27\lib\site-packages\thrift\server\tnonblockingserver.pyc
  c:\python27\lib\site-packages\thrift\server\tnonblockingserver.pyo
  c:\python27\lib\site-packages\thrift\server\tprocesspoolserver.py
  c:\python27\lib\site-packages\thrift\server\tprocesspoolserver.pyc
  c:\python27\lib\site-packages\thrift\server\tprocesspoolserver.pyo
  c:\python27\lib\site-packages\thrift\server\tserver.py
  c:\python27\lib\site-packages\thrift\server\tserver.pyc
  c:\python27\lib\site-packages\thrift\server\tserver.pyo
  c:\python27\lib\site-packages\thrift\thrift.py
  c:\python27\lib\site-packages\thrift\thrift.pyc
  c:\python27\lib\site-packages\thrift\thrift.pyo
  c:\python27\lib\site-packages\thrift\tmultiplexedprocessor.py
  c:\python27\lib\site-packages\thrift\tmultiplexedprocessor.pyc
  c:\python27\lib\site-packages\thrift\tmultiplexedprocessor.pyo
  c:\python27\lib\site-packages\thrift\transport\__init__.py
  c:\python27\lib\site-packages\thrift\transport\__init__.pyc
  c:\python27\lib\site-packages\thrift\transport\__init__.pyo
  c:\python27\lib\site-packages\thrift\transport\sslcompat.py
  c:\python27\lib\site-packages\thrift\transport\sslcompat.pyc
  c:\python27\lib\site-packages\thrift\transport\sslcompat.pyo
  c:\python27\lib\site-packages\thrift\transport\thttpclient.py
  c:\python27\lib\site-packages\thrift\transport\thttpclient.pyc
  c:\python27\lib\site-packages\thrift\transport\thttpclient.pyo
  c:\python27\lib\site-packages\thrift\transport\tsocket.py
  c:\python27\lib\site-packages\thrift\transport\tsocket.pyc
  c:\python27\lib\site-packages\thrift\transport\tsocket.pyo
  c:\python27\lib\site-packages\thrift\transport\tsslsocket.py
  c:\python27\lib\site-packages\thrift\transport\tsslsocket.pyc
  c:\python27\lib\site-packages\thrift\transport\tsslsocket.pyo
  c:\python27\lib\site-packages\thrift\transport\ttransport.py
  c:\python27\lib\site-packages\thrift\transport\ttransport.pyc
  c:\python27\lib\site-packages\thrift\transport\ttransport.pyo
  c:\python27\lib\site-packages\thrift\transport\ttwisted.py
  c:\python27\lib\site-packages\thrift\transport\ttwisted.pyc
  c:\python27\lib\site-packages\thrift\transport\ttwisted.pyo
  c:\python27\lib\site-packages\thrift\transport\tzlibtransport.py
  c:\python27\lib\site-packages\thrift\transport\tzlibtransport.pyc
  c:\python27\lib\site-packages\thrift\transport\tzlibtransport.pyo
  c:\python27\lib\site-packages\thrift\tscons.py
  c:\python27\lib\site-packages\thrift\tscons.pyc
  c:\python27\lib\site-packages\thrift\tscons.pyo
  c:\python27\lib\site-packages\thrift\tserialization.py
  c:\python27\lib\site-packages\thrift\tserialization.pyc
  c:\python27\lib\site-packages\thrift\tserialization.pyo
  c:\python27\lib\site-packages\thrift\ttornado.py
  c:\python27\lib\site-packages\thrift\ttornado.pyc
  c:\python27\lib\site-packages\thrift\ttornado.pyo

**Comment by anysz** [comment]
@anythingg delete manually ??!?

**Comment by anythingg** [comment]
ok. i just created a new vm and started over. the newest version of thrift (0.10.0) was not installed this time so i installed 0.9.3 successfully. the error i was getting meant that i was putting in the wrong email or password. i thought it meant i had to enter my id and password. i entered my email and password into python console (c:\python27\python.exe)  and it appears to be working. thanks.

**Comment by anoaghost** [comment]
![again](https://user-images.githubusercontent.com/26486858/27019406-e6c14876-4f6a-11e7-916b-79c534d3c817.PNG)
who have solution ?

**Comment by Nilpo** [comment]
@anoaghost You have an error in your Python just as it says. Please read the error message and check the indentation in your code.

**Comment by Nilpo** [comment]
@anythingg Glad to see you got it working!

**Comment by RichoDS** [comment]
![untitled](https://user-images.githubusercontent.com/29066224/27105144-5b989cf2-5043-11e7-9f5c-2ea3ab7f2cb1.png)


help

**Comment by anysz** [comment]
Patch the api.py :D @RichoDS

**Comment by Nilpo** [comment]
Or use a newer fork.

**Comment by ii64** [comment]
It was fun guys, Thanks. Issue fixed.
