### ISSUE TITLE
LinGroup Result: AttributeError

### ISSUE THREAD

**Issue by ii64** [carpedm20/LINE#99]
here my code : 
`g = client.groups[3]`
`gc = LineGroup(client, g)`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "C:\Python27\lib\site-packages\line\models.py", line 369, in __init__`
`    self.id            = contact.mid`
`AttributeError: 'LineGroup' object has no attribute 'mid'`

is there somthing wrong with my code? Thanks

**Comment by BloodySenpai** [comment]
Are you trying to do group.mid? If yes don't because LineGroup does not have an attribute ".mid" it's probably "group.id" you're looking for.

**Comment by anysz** [comment]
mid = group.id ?

**Comment by BloodySenpai** [comment]
What are you trying to achieve is my question
What's your line id?

**Comment by anysz** [comment]
So from group.id we can get group.mid?, my line id http://line.me/ti/p/0mYD1NdaOr | http://line.me/ti/p/vdTiVE4Enp

**Comment by theawangatang** [comment]
group.client

group is in group.client

getting group id command and getting attribute (.id) is the group mid

**Comment by theawangatang** [comment]
so look in api...

group = client.group[x] # x is the number group in the list. you can print this list to see its contents

mid = group.id

**Comment by anysz** [comment]
it was old issue. fixed.
